### ISSUE TITLE
/dev/tap devices created on physical host rather than container when running in kind

### ISSUE THREAD

**Issue by detiber** [kubevirt/macvtap-cni#39]
**What happened**:

Trying to run macvtap-cni in a kind cluster results in the /dev/tap devices being created on the physical host rather than the kind container causing pod creation to fail.

**What you expected to happen**:

The /dev/tap devices to be created in the kind container and pod creation to succeed

**How to reproduce it (as minimally and precisely as possible)**:

I created a reproducer using kind/tilt here: https://github.com/detiber/reproducer#reproducer

**Anything else we need to know?**:

**Comment by detiber** [comment]
In trying to dig into it more, it looks like it might be related to devtmpfs not being namespace aware: https://www.redhat.com/archives/libvir-list/2018-July/msg00325.html, not sure if things have changed since then.

**Comment by aviv000** [comment]
I have a workaround,
create your cluster and nodes in cluster.yml with /dev mounted on /dev on the kind host:
Minimal example:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
    propagation: HostToContainer
```
Encountered this myself as well, hopes this helps.
