### ISSUE TITLE
macvtap-cni might terminate in case of stress listing / deleting devices

### ISSUE THREAD

**Issue by oshoval** [kubevirt/macvtap-cni#45]
Create macvtap default empty config (so it will list all device types).

Create 100 bonds, and then delete them all (the delete should trigger the bug).
Increase to 500 if it doesn't happen easily, i managed to simulate it 3 times out of 3 with 500.

```
for i in {1..100}
do
  ip link add bond${i} type bond mode 802.3ad
done
```
```
for i in {1..100}
do
  ip link del bond${i} type bond mode 802.3ad
done
```

**What happened**:

The CNI container terminates and restarts due to fatal error.
(the pod won't look like it restarted, but -oyaml will show the container within actually did)

```
 - containerID: cri-o://5f2673b5c66f84d8dced72ba519d81be006a956241e37fee4cbdeb4127eb3c30
    image: quay.io/kubevirt/macvtap-cni@sha256:f20d5e56f8b8c1ab7e5a64e536b66f65aa688b2d1dc0b37e3c26c2af2b481266
    imageID: quay.io/kubevirt/macvtap-cni@sha256:f20d5e56f8b8c1ab7e5a64e536b66f65aa688b2d1dc0b37e3c26c2af2b481266
    lastState:
      terminated:
        containerID: cri-o://d4327c8e7b871e981b5eba0c997aabd275c871187034f0496188d28ff4e2b40a
        exitCode: 2
        finishedAt: "2021-06-30T09:33:22Z"
        reason: Error
        startedAt: "2021-06-30T08:13:17Z"
```

Reason
```
I0630 09:33:22.050285    6414 manager.go:127] Remove unused plugin "bond1"
I0630 09:33:22.050302    6414 plugin.go:162] bond1: Stopping plugin server
I0630 09:33:22.050307    6414 plugin.go:165] bond1: Tried to stop stopped DPI
fatal error: concurrent map iteration and map write
```

docker stat shown that the cni container consumed 100% CPU and then crashed.
(sometimes it just crashes without showing it)

**What you expected to happen**:
Should be stable.

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:

(possible that those are not relevant - just for consideration)
Maybe need to consider pagination ? (deal the work at batches)
Maybe need to limit the number of go routines so the CPU usage will be capped ?

Is it just a missing lock ? or ` Tried to stop stopped DPI` means 
there is something that was trying to be handled twice?

[Full log of the dead container](https://github.com/kubevirt/macvtap-cni/files/6776248/previous.1.log)
