### ISSUE TITLE
macvtap-cni to connect on layer 2 with other cnis

### ISSUE THREAD

**Issue by fizzers123** [kubevirt/macvtap-cni#99]
**What happened**:

We would like to establish Layer 2 connectivity between different Kubernetes Pods and VMs running on a Kubernetes cluster. This would allow us to deploy networking devices into Kubernetes as routers and switches. This is especially useful for networking labs. 
It would be fantastic if the macvtap-cni would allow connection to other cnis as well (like [kube-ovn](https://www.kube-ovn.io/)) instead of just physical interfaces. 

**What you expected to happen**:

Allow the NetworkAttachmentDefinitionton to use other NetworkAttachmentDefinitions instead of a physical interface.

I am no expert, but something like this would be my vision...

```yaml
--- 
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: other-cni # This is the CNI i would like to use 
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "other-cni.default.ovn"
    }'
---
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: net1 
  annotations: # I want to use another CNI here instead of a physical interface
    k8s.v1.cni.cncf.io/networkName: other-cni.default.ovn 
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "net1",
      "type": "macvtap",
      "mtu": 1500,
      "promiscMode": true
    }'
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-ubuntu-1
spec:
  running: true
  template:
    metadata:
      labels:
        special: vmi-macvtap
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: l2-network
            macvtap: {} # MacVtap as usual to allow l2 thorugh the virt-launcher
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      - name: l2-network
        multus: # Secondary multus network
          networkName: net1

      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                enp2s0:
                  addresses:
                    - 10.0.1.2/24
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
              ssh_authorized_keys:
                - ssh-rsa 
              packages: 
                - qemu-guest-agent
                - lldpd
                - nmap
              runcmd:
                - [ systemctl, start, qemu-guest-agent]
```

**Anything else we need to know?**:

Thanks in advance for any help!
and thanks already for you help in https://github.com/kubevirt/macvtap-cni/issues/97

**Comment by fizzers123** [comment]
I have tried the following configuration. 
The virt-launcher starts successfully, and I the interface is liked correctly to ovn. However, the VM stays in the **Scheduled** state and doesn't start. I have not been able to find any reason for this. Do you have an idea why ? 

```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: virt-lab1-vpc
spec:
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: virt-lab1
spec:
  vpc: virt-lab1-vpc
  provider: net1.default.ovn
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net1
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "net1.default.ovn",
      "promiscMode": true
    }'
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-ubuntu-1
spec:
  running: true
  template:
    metadata:
      labels:
        special: vmi-macvtap
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: l2-network
            macvtap: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      - name: l2-network
        multus: # Secondary multus network
          networkName: net1

      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                enp2s0:
                  addresses:
                    - 10.0.1.2/24
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
              ssh_authorized_keys:
                - ssh-rsa 
              packages: 
                - qemu-guest-agent
                - lldpd
                - nmap
              runcmd:
                - [ systemctl, start, qemu-guest-agent]
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-ubuntu-2
spec:
  running: true
  template:
    metadata:
      labels:
        special: vmi-macvtap
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: l2-network
            macvtap: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      - name: l2-network
        multus: # Secondary multus network
          networkName: net1

      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                enp2s0:
                  addresses:
                    - 10.0.1.3/24
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
              ssh_authorized_keys:
                - ssh-rsa 
              packages: 
                - qemu-guest-agent
                - lldpd
                - nmap
              runcmd:
                - [ systemctl, start, qemu-guest-agent]
```

Interfaces: 
```
110: 2bfd2aa6_net1_h@if109: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether ce:5d:a9:7b:a8:d7 brd ff:ff:ff:ff:ff:ff link-netns cni-930cbdbf-0ee2-10f0-7021-beb7912911a4

netns: cni-930cbdbf-0ee2-10f0-7021-beb7912911a4
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: k6t-eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1400 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
3: tap0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1400 qdisc fq_codel master k6t-eth0 state DOWN mode DEFAULT group default qlen 1000
    link/ether f2:cd:72:d5:b8:27 brd ff:ff:ff:ff:ff:ff
107: eth0@if108: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP mode DEFAULT group default
    link/ether 00:00:00:61:cc:37 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    alias 2bfd2aa6e0de_c
109: net1@if110: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP mode DEFAULT group default
    link/ether 00:00:00:85:77:b9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    alias 2bfd2aa6_net1_c
```
